import axios from "axios";

// CRUD OPERATIONS: 
//// CREATE/POST -
export const ADD_POST_START = "ADD_POST_START"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILURE = "ADD_POST_FAILURE"

//// READ/GET -
export const FETCH_POST_START = "FETCH_POST_START"
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS"
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE"

//// UPDATE/PUT -
export const EDIT_POST_START = "EDIT_POST_START"
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE"

//// DELETE/DELETE -
export const DELETE_POST_START = "DELETE_POST_START"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"